name: Publishing Test Package

on: [pull_request, push]

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            packages: write
            pull-requests: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
                registry-url: pkg.npm.github.com
                always-auth: true
            
            - name: Install dependencies
              run: npm ci

            - name: Publish to GHR
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{github.token}}
            
            - name: Call setup-node with NPM registry
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
                registry-url: registry.npmjs.org
                always-auth: true

            - name: Publish to NPM registry
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}